server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  jackson: #格式化日期
    default-property-inclusion: ALWAYS
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis: #redis
    host: 127.0.0.1 #连接地址
    port: 6379 #端口号
    jedis:
      pool:
        max-active: 8 #连接池中的最大存活连接
        max-idle: 8 #连接池中的最大空闲连接
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 #连接池中的最小空闲连接
    timeout: 100 #连接超时时间（毫秒）
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #配置开启驼峰式命名
  global-config:
    db-config:
      logic-delete-field: delFlag #逻辑删除标志
      logic-delete-value: 1 #逻辑删除
      logic-not-delete-value: 0
      id-type: auto #数据库自增
oss:
  accessKey: IbZL3k9vkvM09u8X1UTxlO_IAM2ekUaNsgamiZAF
  secretKey: 5gyef9v4jDBGILQo4AYjfgxIOMfurdRKm-bcyadu
  bucket: my-self-blog